using Orchard.ContentManagement.MetaData;
using Orchard.Core.Contents.Extensions;
using Orchard.Data.Migration;

// This code was generated by Orchardizer
namespace Hazza.RelatedContent
{
    public class RelatedContentMigration : DataMigrationImpl {
            public int Create() {
            ContentDefinitionManager.AlterPartDefinition("RelatedContentPart", builder => builder
                .Attachable()
                .WithDescription("This will show related content from a lucene search")
            );


            return 1;
        }
    }
}
