
// This code was generated by Orchardizer
namespace Hazza.RelatedContent.Settings
{
    public class RelatedContentPartSettings
    {
		public string Index { get; set; }
		public string Fields { get; set; }
		public int NoOfItems { get; set; }
		public string ContentType { get; set; }
	}
}